version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      CACHE_TTL: ${CACHE_TTL}
      MAX_ITEM_IN_CACHE: ${MAX_ITEM_IN_CACHE}
    depends_on:
      - redis
  redis:
    image: 'redis:6.0.10-alpine'
